package dbml;
// Generated 13/09/2014 01:29:31 PM by Hibernate Tools 3.6.0



/**
 * Amigo generated by hbm2java
 */
public class Amigo  implements java.io.Serializable {


     private Integer idAmigo;
     private String foto;
     private String nombres;
     private String correo;
     private String telf;
     private int estado;

    public Amigo() {
    }

	
    public Amigo(int estado) {
        this.estado = estado;
    }
    public Amigo(String foto, String nombres, String correo, String telf, int estado) {
       this.foto = foto;
       this.nombres = nombres;
       this.correo = correo;
       this.telf = telf;
       this.estado = estado;
    }
   
    public Integer getIdAmigo() {
        return this.idAmigo;
    }
    
    public void setIdAmigo(Integer idAmigo) {
        this.idAmigo = idAmigo;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelf() {
        return this.telf;
    }
    
    public void setTelf(String telf) {
        this.telf = telf;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


