package dbml;
// Generated 13/09/2014 01:29:31 PM by Hibernate Tools 3.6.0



/**
 * Demo generated by hbm2java
 */
public class Demo  implements java.io.Serializable {


     private Integer idnewTable;
     private String demo;

    public Demo() {
    }

    public Demo(String demo) {
       this.demo = demo;
    }
   
    public Integer getIdnewTable() {
        return this.idnewTable;
    }
    
    public void setIdnewTable(Integer idnewTable) {
        this.idnewTable = idnewTable;
    }
    public String getDemo() {
        return this.demo;
    }
    
    public void setDemo(String demo) {
        this.demo = demo;
    }




}


