package dbml;
// Generated 13/09/2014 01:29:31 PM by Hibernate Tools 3.6.0



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private Integer iddomicilio;
     private String calle;
     private String colonia;
     private String ciudad;

    public Domicilio() {
    }

    public Domicilio(String calle, String colonia, String ciudad) {
       this.calle = calle;
       this.colonia = colonia;
       this.ciudad = ciudad;
    }
   
    public Integer getIddomicilio() {
        return this.iddomicilio;
    }
    
    public void setIddomicilio(Integer iddomicilio) {
        this.iddomicilio = iddomicilio;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


