package dbml;
// Generated 13/09/2014 01:29:31 PM by Hibernate Tools 3.6.0



/**
 * Uno generated by hbm2java
 */
public class Uno  implements java.io.Serializable {


     private int iduno;
     private String unocol;

    public Uno() {
    }

	
    public Uno(int iduno) {
        this.iduno = iduno;
    }
    public Uno(int iduno, String unocol) {
       this.iduno = iduno;
       this.unocol = unocol;
    }
   
    public int getIduno() {
        return this.iduno;
    }
    
    public void setIduno(int iduno) {
        this.iduno = iduno;
    }
    public String getUnocol() {
        return this.unocol;
    }
    
    public void setUnocol(String unocol) {
        this.unocol = unocol;
    }




}


